### ISSUE TITLE
(not an issue but a request)

### ISSUE THREAD

**Issue by rahulbanwasi** [FlyingFathead/TelegramBot-OpenAI-API#1]
can you please add pdf mode too? so that we send the pdf through telegram to the bot and using the perplexity pro ai we can ask anything wrt to the pdf content? it will be a huge help

**Comment by FlyingFathead** [comment]
Hi @rahulbanwasi!

Thanks for the suggestion! 

I'd like that kind of a feature too, however implementing it would have to write the PDF transcription module separately, and Perplexity's API is limited as to what features you get out of it -- for instance, the real-time information is there, but it's not always on-par with the Perplexity Pro's own web searches. 

Also, adding file uploads via API doesn't seem to be on their roadmap, according to [this forum post](https://docs.perplexity.ai/discuss/65826db7e1fdf400782d2656) or [Perplexity's own roadmap](https://docs.perplexity.ai/docs/feature-roadmap). 

PDF conversion has always been a bit of a hassle, whether it's about scraping the text layers correctly, or, if there are no text layers, getting the text read correctly using OCR. 

I would perhaps suggest using GPT-4o via the API on this, since it's currently the leader in terms of visual recognition capabilities (although it can stagger at times as well), see [docs for GPT-4o vision](https://platform.openai.com/docs/guides/vision).

If you're interested in extracting data from PDF's, I also have a side project that I used for scraping the text layers in a coherent format out of PDF's, it's at: [https://github.com/FlyingFathead/PDF-translator-OpenAI-API](https://github.com/FlyingFathead/PDF-translator-OpenAI-API) and can also be used for OpenAI API based translations. The thing is though, that it only works when there's a text layer in the PDF (there's currently no computer vision/OCR feature support in it). 

As for OCR projects, I've also made a separate Python program called [OCR-CopyPastePad](https://github.com/FlyingFathead/OCR-CopyPastePad) that uses a combination of different user-selectable OCR methods such as `pytesseract` and `easyocr` for reading text from bitmap image files. Perhaps some of these projects could be of assistance to you?

What I'd personally recommend, and if I'd implement the feature, I would likely do it with GPT-4o's vision module, so that any possible text layers get extracted and added in as a supplementary anchoring data for the model, and then we'd use a combination of the vision model and the LLM to format the text output. This could then be added to a file-specific database so that you'd only be importing and reading a PDF once into your model's RAG database.

These are of course just ramblings of a madman, so take them for what they are. :o)

Maybe if I have the time later on at some point, I can look into this. Thanks so much for your suggestion. Cheers!
